
name: Publish to npm

on:
  workflow_dispatch:
  push:
    tags:
      - '*'          # e.g. v1.0.0
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify tag matches package.json version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          echo "package.json version: $PKG_VERSION"
          echo "tag version:        $TAG_VERSION"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "::error::Tag $TAG_VERSION does not match package.json version $PKG_VERSION"
            exit 1
          fi

      - name: Install (no build needed)
        run: npm ci --ignore-scripts || npm install --ignore-scripts

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
